name: deploy-static-webapp

on:
  push:
    branches: [master]

concurrency:
  group: deploy-static-webapp
  cancel-in-progress: true

permissions:
  id-token: write
  contents: read

jobs:
  deploy-dev:
    environment: dev
    name: deploy-dev
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install + build
        run: npm install && npm run build

      - name: Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: "upload"
          skip_app_build: true
          app_location: "dist"

  deploy-prod:
    environment: prod
    needs: deploy-dev
    name: deploy-prod
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install + build
        run: npm install && npm run build

      - name: Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: "upload"
          skip_app_build: true
          app_location: "dist"
